[versions]
composeMultiplatform = "1.9.0-beta01"
kotlin = "2.2.20-Beta2"
composeHotReload = "1.0.0-beta04"
jna = "5.13.0"

[libraries]
kotlin-wrapper-browser= { group = "org.jetbrains.kotlin-wrappers", name = "kotlin-browser", version = "2025.8.6" }
desktop-media-vlc = { module = "uk.co.caprica:vlcj", version = "4.11.0" }
jna = { module = "net.java.dev.jna:jna", version.ref = "jna" }
jna-platform = { module = "net.java.dev.jna:jna-platform", version.ref = "jna" }

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }

